version: '3.3'
services:
  chartjs-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./.env
